name: POC-1 AWS CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  APP_NAME: poc1-cicd-app
  ENV_NAME: poc1-env

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Infrastructure (CloudFormation)
        run: |
          aws cloudformation deploy \
            --template-file infra/eb.yml \
            --stack-name poc1-eb-stack \
            --parameter-overrides \
              AppName=${{ env.APP_NAME }} \
              EnvironmentName=${{ env.ENV_NAME }} \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Zip Application
        run: |
          cd app
          zip -r ../app.zip .

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ env.APP_NAME }} \
            --version-label v-${{ github.run_id }} \
            --source-bundle S3Bucket=elasticbeanstalk-${{ env.AWS_REGION }}-${{ secrets.AWS_ACCOUNT_ID }},S3Key=app.zip

          aws elasticbeanstalk update-environment \
            --environment-name ${{ env.ENV_NAME }} \
            --version-label v-${{ github.run_id }}
